import type { EventCatalog } from '../catalog/index.js';

import { emitPayloadInterfaces } from './catalog-sections.js';
import { emitSchemaRegistryConfigConstant } from './metadata-sections.js';
import { emitClientFactory, emitClientTypes } from './minimal-client-sections.js';
import {
  emitConsumerFactory,
  emitConsumerTypes
} from './minimal-consumer-sections.js';
import { emitConsumerMessageTypes } from './minimal-message-sections.js';
import {
  emitMinimalConsumerMetadata,
  emitMinimalProducerMetadata
} from './minimal-metadata-sections.js';
import {
  emitProducerFactory,
  emitProducerTypes
} from './minimal-producer-sections.js';
import { formatLiteral } from './render-utils.js';
import type { GeneratedFile } from './types.js';

export function emitMinimalGeneratedFile(catalog: EventCatalog): GeneratedFile {
  const sections = [
    '// Generated by kafka-typegen. Do not edit manually.',
    `import type { RuntimeClient, RuntimeConsumer, RuntimeEventMetadata, RuntimeProducer } from ${formatLiteral(catalog.config.runtime.module)};`,
    emitPayloadInterfaces(catalog),
    ...(catalog.config.schemaRegistry !== undefined
      ? [emitSchemaRegistryConfigConstant(catalog) ?? '']
      : []),
    emitConsumerMessageTypes(catalog),
    emitMinimalProducerMetadata(catalog),
    emitMinimalConsumerMetadata(catalog),
    emitProducerTypes(catalog),
    emitProducerFactory(catalog),
    emitConsumerTypes(catalog),
    emitConsumerFactory(catalog),
    emitClientTypes(),
    emitClientFactory()
  ];

  return {
    contents: `${sections.join('\n\n')}\n`,
    filePath: catalog.config.generation.typesFileName
  };
}
