import type { EventCatalog } from '../catalog/index.js';

import { emitPayloadInterfaces, emitEventUnion, emitTopicUnion, emitEventPayloadMap, emitTopicEventsMap } from './catalog-sections.js';
import { emitClientFactory, emitClientTypes } from './client-sections.js';
import { emitConsumerFactory, emitConsumerTypes } from './consumer-sections.js';
import {
  emitEventMetadataMap,
  emitProducerMetadataConstant,
  emitSchemaRegistryConfigConstant,
  emitTopicMetadataConstant,
  emitTopicMetadataMap
} from './metadata-sections.js';
import { emitEventNameConstants, emitTopicNameConstants } from './name-sections.js';
import { emitGeneratedIndexFile } from './package-files.js';
import { emitProducerFactory, emitProducerTypes } from './producer-sections.js';
import { formatLiteral } from './render-utils.js';
import type { GeneratedFile, GeneratorOutput, TypeGenerator } from './types.js';

function emitGeneratedFile(catalog: EventCatalog): GeneratedFile {
  const sections = [
    '// Generated by kafka-typegen. Do not edit manually.',
    `import type { RuntimeClient, RuntimeConsumer, RuntimeEventMetadata, RuntimeProducer } from ${formatLiteral(catalog.config.runtime.module)};`,
    emitPayloadInterfaces(catalog),
    emitEventUnion(catalog),
    emitTopicUnion(catalog),
    emitEventNameConstants(catalog),
    emitTopicNameConstants(catalog),
    ...(catalog.config.schemaRegistry !== undefined
      ? [emitSchemaRegistryConfigConstant(catalog) ?? '']
      : []),
    emitEventPayloadMap(catalog),
    emitTopicEventsMap(catalog),
    emitEventMetadataMap(catalog),
    emitTopicMetadataMap(catalog),
    emitProducerMetadataConstant(catalog),
    emitTopicMetadataConstant(catalog),
    emitProducerTypes(catalog),
    emitProducerFactory(catalog),
    emitConsumerTypes(catalog),
    emitConsumerFactory(catalog),
    emitClientTypes(),
    emitClientFactory()
  ];

  return {
    contents: `${sections.join('\n\n')}\n`,
    filePath: catalog.config.generation.typesFileName
  };
}

export class DefaultTypeGenerator implements TypeGenerator {
  public async generate(catalog: EventCatalog): Promise<GeneratorOutput> {
    const indexFile = emitGeneratedIndexFile(catalog);

    return {
      files: [
        emitGeneratedFile(catalog),
        ...(indexFile !== undefined ? [indexFile] : [])
      ]
    };
  }
}

export function createTypeGenerator(): TypeGenerator {
  return new DefaultTypeGenerator();
}
